USE Blog_Community
GO


ALTER TABLE dbo.NEWFEEDPOST
ADD Emotion TINYINT
GO

ALTER TABLE dbo.NEWFEEDPOST
ADD Images NVARCHAR(MAX)
GO

ALTER TABLE dbo.USERINFO
ADD Avatar NVARCHAR(256)
GO

ALTER TABLE dbo.USERINFO
ADD Cover NVARCHAR(256)
GO

ALTER TABLE dbo.ALBUMMUSIC
ADD Cover NVARCHAR(MAX)
GO

ALTER TABLE dbo.ALBUMIMAGES 
ADD Cover NVARCHAR(MAX)
GO

ALTER TABLE dbo.ALBUMVIDEOS
ADD Cover NVARCHAR(MAX)
GO

ALTER TABLE dbo.ALBUMMUSIC
ADD UpdatedTS DATETIME2
GO


ALTER TABLE dbo.ALBUMVIDEOS
ADD UpdatedTS DATETIME2
GO






CREATE TABLE LIKEPOST
(
	IdPost NVARCHAR(128),
	IdUser NVARCHAR(128),
	Status TINYINT,
	PRIMARY KEY (IdPost,IdUser),

	CONSTRAINT FK_UserAccount_IdUser_USERACCOUNT
	FOREIGN KEY (IdUser)
	REFERENCES dbo.USERACCOUNT(IdUser)
)
GO

CREATE TABLE USERSEXCLUDE
(
	IdUser NVARCHAR(128),
	IdUserExclude NVARCHAR(128),
	Status TINYINT,

	PRIMARY KEY(IdUser, IdUserExclude),

	CONSTRAINT FK_USERACCOUNT_IdUser_USERSEXCLUDE 
	FOREIGN KEY (IdUser)
	REFERENCES dbo.USERACCOUNT(IdUser),

	CONSTRAINT FK_USERACCOUNT_IdUserExclude_USERSEXCLUDE 
	FOREIGN KEY (IdUserExclude)
	REFERENCES dbo.USERACCOUNT(IdUser)
)

GO

ALTER TABLE dbo.NEWFEEDPOST
ADD SharePost NVARCHAR(128)
GO


CREATE TABLE REPLYCOMMENT
(
	IdReply NVARCHAR(128) PRIMARY KEY,
	IdComment NVARCHAR(128),
	IdUser NVARCHAR(128),
	Content NVARCHAR(MAX),
	CreatedTS DATETIME2,
	UpdatedTS DATETIME2,

	CONSTRAINT FK_COMMENT_IdUser_REPLY
	FOREIGN KEY (IdComment)
	REFERENCES dbo.COMMENT(IdComment),

	CONSTRAINT FK_REPLY_IdUser_USERACCOUNT
	FOREIGN KEY (IdUser)
	REFERENCES dbo.USERACCOUNT(IdUser),
)
GO

ALTER TABLE dbo.COMMENT
ADD Images NVARCHAR(MAX)

GO

ALTER TABLE dbo.REPLYCOMMENT
ADD Images NVARCHAR(MAX)

GO


